### ISSUE TITLE
futhark

### ISSUE THREAD

**Issue by sun0912704** [topopt/futtop#2]
what is the futhark compiler?or which compiler is for futhark?

**Comment by Traffelaffen** [comment]
The futhark compiler is available from their project website https://futhark-lang.org/

Last I compiled the project I used v 0.21.11.

**Comment by sun0912704** [comment]
Thanks for your guidance, I have successfully installed the futhark compiler and GCC through your guidance. But I met a new problem, as shown in the picture: I don't know how to solve it, please give me some advice.
![79434e53012ee3d249d2ba1c91f687e](https://github.com/topopt/futtop/assets/62976651/f26efef6-d7e9-4218-be4b-e41bcf3776b5)
 In addition, I also want to confirm whether the last command of your code is correct. There is no top3d.c file in the futtop file.
![99a95c13fdb16d532d55cdc686e7aa5](https://github.com/topopt/futtop/assets/62976651/f80d6fc3-6343-457e-b390-178d2e6d47a8)
